games = [
    ['dota2', 'dota', 'дота', 'дотан', 'дотка'],
    ['cs', "кс", "контра"],
    ['wow', 'world of warcraft', "вов"],
    ['lol', 'league of legends', 'лол'],
    ['overwatch', 'овервотч'],
    ['blade and soul', 'bs','бс'],
    ['battlefield', 'батла'],
    ['revelation'],
    ['wot', 'world of tanks'],
    ['bd', 'black desert'],
    ['hots', 'heroes of the storm', 'хотс'],
    ['minecraft', 'майнкрафт'],
    ['hs','hearthstone'],
    ['sf', 'сф', 'skyforge', 'скайфордж'],
    ['wt', 'war thunder'],
    ['smite'],
    ['world of warships'],
    ['paragon'],
    ['mb','moonlight blade'],
    ['tera', 'tera online', 'тера'],
    ['tf', 'тф', 'team fortress', 'team fortress 2'],
    ['travian', 'травиан'],
    ['allods', 'аллоды', 'allods online'],
    ['aion', 'айон'],
    ['loa', 'league of angels', 'league of angels 2'],
    ['gta', 'gta online'],
    ['warface', 'wf'],
    ['doom', 'дум'],
    ['lineage', 'lineage 2'],
    ['neverwinter'],
    ['panzar'],
    ['pw', 'perfect world']
]